### ISSUE TITLE
Player LL-HLS config page is broken 

### ISSUE THREAD

**Issue by luwes** [THEOplayer/documentation#3]
this url is broken 
https://docs.theoplayer.com/how-to-guides/07-miscellaneous/03-low-latency/02-configure-ll-hls.md

**Comment by ceyhun-o** [comment]
Hi @luwes,

Since THEOplayer 4.0, you do not need to configure anything to get your LL-HLS stream working. Simply setting the source is enough and our player will handle the rest. The outdated pages are removed from our documentation to not cause confusion.

You can test your LL-HLS stream on our demo player: https://www.theoplayer.com/test-your-stream-hls-dash-hesp

Kind regards,
Ceyhun
